Допустим, у нас есть $n$ товаров с заданными стоимостями $v_i$ и массой $w_i$. В сумку убирается $С$ кг. Сколько какого товара взять, чтобы сумма всех стоимостей товаров была наибольшей?

In [1]:
values = [4, 20, 1, 5, 3, 10]
weights = [5, 10, 2, 5, 6, 6]
C = 19
n = 6

Сформулируем задачу:
$$\max\sum v_i x_i$$
$$\sum w_i x_i \leq C $$

Как должна выглядеть задача:
$$\min c^T x$$
$$A x \leq b $$

Получается, что $c=-v$, $A=w^T$, $b=(C)$

In [2]:
import numpy as np

In [3]:
c = - np.array(values)
A = np.array(weights)         #shape = (6,)
A = np.expand_dims(A, 0)      #shape = (1,6)
b = np.array([C])

In [4]:
from scipy.optimize import linprog

In [5]:
linprog(c=c, A_ub=A, b_ub=b)

     con: array([], dtype=float64)
     fun: -38.000000003742656
 message: 'Optimization terminated successfully.'
     nit: 4
   slack: array([-3.30540573e-09])
  status: 0
 success: True
       x: array([1.42705575e-11, 1.90000000e+00, 3.55393213e-11, 3.84018664e-11,
       2.12247194e-10, 2.86840312e-10])

In [6]:
import cvxpy

In [7]:
x = cvxpy.Variable(shape=n, integer = True)

In [8]:
constraint = (A @ x <= b)
total_value = c * x

C:\Users\SVasilchenko\anaconda3\lib\site-packages\cvxpy\expressions\expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 1 times so far.

  warnings.warn(msg, UserWarning)


In [9]:
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint])

In [10]:
problem.solve(solver='ECOS_BB')

-159383570.99999994

In [11]:
x.value.round(0)

array([-8388608.,  8388608., -8388608., -5033161., -8388608.,  8388608.])

Теперь положительные $x$

In [12]:
x = cvxpy.Variable(shape=n, integer=True)
constraint = (A @ x <= b)
x_positive = (x >= 0)
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve(solver='ECOS_BB')

C:\Users\SVasilchenko\anaconda3\lib\site-packages\cvxpy\expressions\expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 2 times so far.

  warnings.warn(msg, UserWarning)


-31.000000028568287

In [13]:
x.value.round(0)

array([0., 1., 1., 0., 0., 1.])

Теперь $x = 0$ или $1$

In [14]:
x = cvxpy.Variable(shape=n, boolean=True)
constraint = A @ x <= b
x_positive = x >= 0
total_value = c * x
problem = cvxpy.Problem(cvxpy.Minimize(total_value), constraints=[constraint, x_positive])
problem.solve(solver='ECOS_BB')

C:\Users\SVasilchenko\anaconda3\lib\site-packages\cvxpy\expressions\expression.py:556: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 3 times so far.

  warnings.warn(msg, UserWarning)


-31.000000028568287

In [15]:
x.value.round(0)

array([0., 1., 1., 0., 0., 1.])