In [1]:
import numpy as np

In [2]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[1, 8, 1],
       [3, 6, 1],
       [4, 8, 1]])

In [3]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [5]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [6]:
my_array = np.array([x for x in range(10)])
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [7]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48],[85,86,87,88]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48],
       [85, 86, 87, 88]])

In [8]:
my_array[:,-3:]

array([[ 2,  3,  4],
       [11, 12, 13],
       [46, 47, 48],
       [86, 87, 88]])

In [9]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

summ = 0
for item in big_secret[:,-1]:
    summ += item
print(summ)
    
big_secret[:,-1].sum()    

3154.332495807108


3154.332495807108

In [10]:
ar = big_secret[:,:5]
summ = 0
for i in range(0,5):
    summ += ar[i,i]
summ

121.37188663699624

In [11]:
ar = big_secret[:,-5:]
mult = 1
for i in range(0,5):
    mult *= ar[i,i]
mult

341505315559.2347

In [12]:
for i in range(0, 5, 2):
    for j in range(0, big_secret.shape[1]+1, 2):
        big_secret[i,j] = -1
        
for i in range(1, 5, 2):
    for j in range(1, big_secret.shape[1], 2):
        big_secret[i,j] = 1
        
ar = big_secret[:,:5]

summ = 0
for i in range(0,5):
    summ += ar[i,i]
    
summ

-1.0

In [13]:
ar = big_secret[:,-5:]

mult = 1
for i in range(0,5):
    mult *= ar[i,i]
mult

-1.0

In [14]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1,
                                                                                              result2,
                                                                                              result3,
                                                                                              result4,
                                                                                              result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [15]:
my_array = np.random.randint(0, 10, (3,4))
my_array

array([[0, 2, 6, 4],
       [1, 2, 4, 6],
       [2, 3, 9, 4]])

In [16]:
my_array < 5

array([[ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [17]:
my_array[my_array<5]

array([0, 2, 4, 1, 2, 4, 2, 3, 4])

In [18]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[0, 6],
       [1, 4],
       [2, 9]])

In [19]:
row_mask = np.array([0, 1, 1], dtype=bool)
my_array[row_mask,:]

array([[1, 2, 4, 6],
       [2, 3, 9, 4]])

In [20]:
my_array = np.random.randint(0, 10, (4, 6))
my_array

array([[8, 1, 6, 9, 3, 2],
       [4, 2, 5, 6, 4, 5],
       [0, 1, 3, 8, 5, 9],
       [8, 7, 3, 9, 4, 9]])

In [21]:
np.sort(my_array, axis=0)

array([[0, 1, 3, 6, 3, 2],
       [4, 1, 3, 8, 4, 5],
       [8, 2, 5, 9, 4, 9],
       [8, 7, 6, 9, 5, 9]])

In [22]:
np.sort(my_array, axis=1)

array([[1, 2, 3, 6, 8, 9],
       [2, 4, 4, 5, 5, 6],
       [0, 1, 3, 5, 8, 9],
       [3, 4, 7, 8, 9, 9]])

In [23]:
my_array

array([[8, 1, 6, 9, 3, 2],
       [4, 2, 5, 6, 4, 5],
       [0, 1, 3, 8, 5, 9],
       [8, 7, 3, 9, 4, 9]])

In [24]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [25]:
np.cos(great_secret[0,:]).sum()

0.16006721889793019

In [26]:
summ = 0
for x in np.nditer(great_secret):
    if x > 50:
        summ += x
    
summ

5470.0

In [28]:
great_secret.flatten()[150]

7.0710678118654755

In [29]:
np.sort(great_secret, axis=0)[-1,:].sum()

115.12148016521353

In [35]:
pupils = np.array([[1, 135, 34, 4],
[2, 160, 43, 5],
[3, 163, 40, 4.3],
[4, 147, 44, 5],
[5, 138, 41, 4.7],
[6, 149, 54, 3.9],
[7, 136, 39, 4.2],
[8, 154, 48, 4.9],
[9, 137, 35, 3.7],
[10, 165, 60, 4.6]])

In [36]:
mass_median = np.median(pupils[:,2])
mass_mean = np.mean(pupils[:,2])
mass_mean - mass_median

1.7999999999999972

In [40]:
corr = np.corrcoef(pupils[:,2], pupils[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [41]:
std_marks = np.std(pupils[:,3])
std_marks

0.4517742799230607

In [42]:
np.std(pupils[:,2])**2

60.36

In [43]:
np.random.randint(1, 10, (10, 10))

array([[6, 5, 5, 3, 2, 7, 9, 1, 9, 4],
       [4, 2, 8, 7, 5, 1, 1, 5, 9, 9],
       [4, 8, 8, 6, 2, 3, 3, 2, 4, 7],
       [7, 8, 1, 9, 9, 4, 8, 5, 9, 7],
       [4, 5, 3, 1, 3, 7, 6, 3, 8, 7],
       [3, 1, 9, 7, 6, 1, 9, 3, 2, 7],
       [7, 9, 6, 7, 1, 2, 6, 8, 7, 4],
       [8, 9, 4, 3, 7, 1, 1, 9, 2, 7],
       [4, 7, 5, 9, 6, 3, 7, 5, 3, 8],
       [3, 1, 2, 1, 7, 3, 8, 2, 6, 1]])

In [51]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [49]:
my_sin = np.sin(my_array)
np.sum(my_sin)

-0.05812430261413351

In [56]:
my_sin[1:4,1:4] = 1
np.sum(my_sin)

7.571718421269144

In [58]:
my_sin[:,0:4].reshape((10,2))[:,0].sum()

2.4057172058139544

In [61]:
bigdata = [x**2 for x in range(101, 1000, 2)]
np.median(bigdata)

302501.0

In [62]:
np.std(bigdata)

292095.0301991155