In [2]:
import numpy as np

In [3]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[0, 5, 9],
       [3, 9, 2],
       [9, 7, 2]])

In [4]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
np.array([[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]) 

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [6]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [7]:
my_array = np.array([x for x in range(10)])
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [15]:
my_array = np.array([[1,2,3,4], [10,11,12,13], [45,46,47,48],[85,86,87,88]])
my_array

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13],
       [45, 46, 47, 48],
       [85, 86, 87, 88]])

In [59]:
my_array[:,-3:]

array([[ 2,  3,  4],
       [11, 12, 13],
       [46, 47, 48],
       [86, 87, 88]])

In [37]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

summ = 0
for item in big_secret[:,-1]:
    summ += item
print(summ)
    
big_secret[:,-1].sum()    

3154.332495807108


3154.332495807108

In [47]:
ar = big_secret[:,:5]
summ = 0
for i in range(0,5):
    summ += ar[i,i]
summ

121.37188663699624

In [62]:
ar = big_secret[:,-5:]
mult = 1
for i in range(0,5):
    mult *= ar[i,i]
mult

341505315559.2347